import type { Poi } from "./types";
import { assertValidPoiDataset } from "./poi-validation";

/**
 * Seeded central-Paris POI dataset.
 * MOCK DATA LAYER — see ./services.ts. Swap for Overpass / Wikidata / OpenTripMap
 * without touching the routing engine or UI.
 */
const CURATED_POIS: Poi[] = [
  {
    id: "palais-royal",
    name: "Palais Royal",
    lat: 48.8637,
    lng: 2.3372,
    category: "Palace & Courtyard",
    kicker: "Iconic Paris · Architecture",
    description:
      "A 17th-century royal palace whose courtyard holds Buren's striped columns — a favourite Parisian shortcut.",
    detail:
      "Built for Cardinal Richelieu in 1633 and later home to the Duke of Orléans, the Palais Royal now houses the Conseil d'État. The Cour d'Honneur was filled in 1986 with Daniel Buren's 260 striped columns, an installation that scandalised the city and is now one of its most photographed courtyards.",
    scores: {
      scenic: 9,
      hidden: 3,
      historic: 9,
      architecture: 10,
      nature: 5,
      food: 4,
      popularity: 8,
    },
    interests: ["architecture", "historic", "iconic", "art"],
    visitMinutes: 8,
    arrondissement: 1,
    neighborhood: "Palais Royal",
  },
  {
    id: "jardin-palais-royal",
    name: "Jardin du Palais Royal",
    lat: 48.865,
    lng: 2.3376,
    category: "Garden",
    kicker: "Parks & Gardens · Local Paris",
    description:
      "An arcaded garden of clipped limes and fountains, sealed off from the traffic on all four sides.",
    detail:
      "One of the calmest places in the 1st arrondissement: gravel walks, a central fountain, and galleries of old-fashioned shops selling medals, pipes and antique toys. Colette lived above the north-west arcade for the last years of her life.",
    scores: {
      scenic: 9,
      hidden: 4,
      historic: 8,
      architecture: 8,
      nature: 9,
      food: 5,
      popularity: 7,
    },
    interests: ["parks", "quiet", "romantic", "architecture"],
    visitMinutes: 10,
    arrondissement: 1,
    neighborhood: "Palais Royal",
  },
  {
    id: "galerie-vivienne",
    name: "Galerie Vivienne",
    lat: 48.8664,
    lng: 2.3402,
    category: "Historic Passage",
    kicker: "Hidden Gem · Architecture",
    description:
      "One of Paris's most elegant covered passages, opened in 1826, known for mosaic floors and a glass roof.",
    detail:
      "Neoclassical goddesses, nymphs and garlands run above shopfronts; underfoot, Giandomenico Facchina's mosaic. The passage still holds a century-old bookshop, a wine merchant and a tearoom, and it stays dry and quiet whatever the weather is doing on rue Vivienne.",
    scores: {
      scenic: 10,
      hidden: 7,
      historic: 9,
      architecture: 10,
      nature: 1,
      food: 6,
      popularity: 6,
    },
    interests: ["architecture", "hidden", "historic", "bookshops", "romantic"],
    visitMinutes: 7,
    arrondissement: 2,
    neighborhood: "Bourse",
  },
  {
    id: "passage-panoramas",
    name: "Passage des Panoramas",
    lat: 48.8712,
    lng: 2.3416,
    category: "Historic Passage",
    kicker: "Historic Paris · Food",
    description:
      "The oldest covered passage in Paris, 1799 — now a crowded little corridor of stamp dealers and bistros.",
    detail:
      "The first Paris arcade lit by gas. Today it is scruffier and livelier than Vivienne: philatelists, engravers, and a dense row of small restaurants where locals eat elbow to elbow at lunchtime.",
    scores: {
      scenic: 8,
      hidden: 6,
      historic: 10,
      architecture: 7,
      nature: 1,
      food: 9,
      popularity: 6,
    },
    interests: ["historic", "hidden", "food", "local", "architecture"],
    visitMinutes: 8,
    arrondissement: 2,
    neighborhood: "Grands Boulevards",
  },
  {
    id: "passage-grand-cerf",
    name: "Passage du Grand Cerf",
    lat: 48.8646,
    lng: 2.3496,
    category: "Historic Passage",
    kicker: "Hidden Gem · Art & Galleries",
    description:
      "The tallest of the arcades, twelve metres of glass roof above independent design studios.",
    detail:
      "Rebuilt in 1825 on the site of a coaching inn, the Grand Cerf has the highest glazed roof of any Paris passage. Its tenants are mostly makers — jewellers, lighting designers, a bead shop — and it is usually almost empty.",
    scores: {
      scenic: 8,
      hidden: 9,
      historic: 8,
      architecture: 9,
      nature: 1,
      food: 4,
      popularity: 3,
    },
    interests: ["hidden", "architecture", "art", "quiet", "local"],
    visitMinutes: 6,
    arrondissement: 2,
    neighborhood: "Montorgueil",
  },
  {
    id: "rue-montorgueil",
    name: "Rue Montorgueil",
    lat: 48.865,
    lng: 2.3468,
    category: "Market Street",
    kicker: "Local Favorite · Food",
    description:
      "A pedestrian market street of fishmongers, cheese counters and terraces that never quite empties.",
    detail:
      "The surviving spine of the old Les Halles food quarter. Stohrer, opened 1730 by Louis XV's pastry chef, still sells baba au rhum halfway down. Best late morning, when the stalls are out and the street belongs to the neighbourhood.",
    scores: {
      scenic: 7,
      hidden: 3,
      historic: 7,
      architecture: 5,
      nature: 1,
      food: 10,
      popularity: 8,
    },
    interests: ["food", "cafes", "local", "historic"],
    visitMinutes: 12,
    arrondissement: 2,
    neighborhood: "Montorgueil",
  },
  {
    id: "saint-eustache",
    name: "Église Saint-Eustache",
    lat: 48.8635,
    lng: 2.3452,
    category: "Church",
    kicker: "Architecture · Historic Paris",
    description:
      "Gothic bones in Renaissance dress, with the largest pipe organ in France.",
    detail:
      "A hundred years in the building (1532–1632), Saint-Eustache carries Gothic vaults on classical columns. Molière was baptised here, Louis XIV took communion here, and the organ recitals on Sunday afternoons are free.",
    scores: {
      scenic: 8,
      hidden: 5,
      historic: 9,
      architecture: 10,
      nature: 1,
      food: 2,
      popularity: 6,
    },
    interests: ["architecture", "historic", "art"],
    visitMinutes: 10,
    arrondissement: 1,
    neighborhood: "Les Halles",
  },
  {
    id: "place-des-vosges",
    name: "Place des Vosges",
    lat: 48.8555,
    lng: 2.3655,
    category: "Square",
    kicker: "Iconic Paris · Architecture",
    description:
      "The oldest planned square in Paris: red brick, blue slate, and thirty-six identical pavilions.",
    detail:
      "Completed in 1612 as the Place Royale. The arcades run unbroken around all four sides, the lawns fill with readers on any warm afternoon, and Victor Hugo's apartment at number 6 is free to visit.",
    scores: {
      scenic: 10,
      hidden: 2,
      historic: 10,
      architecture: 10,
      nature: 7,
      food: 5,
      popularity: 9,
    },
    interests: ["iconic", "architecture", "historic", "parks", "romantic"],
    visitMinutes: 12,
    arrondissement: 4,
    neighborhood: "Le Marais",
  },
  {
    id: "jardin-anne-frank",
    name: "Jardin Anne Frank",
    lat: 48.8613,
    lng: 2.3577,
    category: "Garden",
    kicker: "Hidden Gem · Parks & Gardens",
    description:
      "A walled garden hidden behind a Marais courtyard, with a cutting from the Amsterdam chestnut tree.",
    detail:
      "Reached through an unmarked passage off impasse Berthaud. Three linked garden rooms — a pergola, an orchard, a lawn — almost nobody finds them by accident. A sapling grown from the chestnut Anne Frank watched from the annexe grows here.",
    scores: {
      scenic: 8,
      hidden: 10,
      historic: 6,
      architecture: 4,
      nature: 10,
      food: 1,
      popularity: 2,
    },
    interests: ["hidden", "parks", "quiet", "local"],
    visitMinutes: 8,
    arrondissement: 3,
    neighborhood: "Le Marais",
  },
  {
    id: "hotel-soubise",
    name: "Hôtel de Soubise",
    lat: 48.86,
    lng: 2.3595,
    category: "Mansion",
    kicker: "Architecture · Historic Paris",
    description:
      "A rococo palace behind a colonnaded court of honour, now the National Archives.",
    detail:
      "The 1375 medieval turrets on rue des Archives belong to the older Hôtel de Clisson; behind them, Delamair's 1705 horseshoe courtyard opens onto some of the finest rococo interiors in France. The garden at the back is public and almost always empty.",
    scores: {
      scenic: 9,
      hidden: 7,
      historic: 10,
      architecture: 10,
      nature: 5,
      food: 1,
      popularity: 4,
    },
    interests: ["architecture", "historic", "hidden", "art"],
    visitMinutes: 10,
    arrondissement: 3,
    neighborhood: "Le Marais",
  },
  {
    id: "marche-enfants-rouges",
    name: "Marché des Enfants Rouges",
    lat: 48.8632,
    lng: 2.3625,
    category: "Covered Market",
    kicker: "Food · Local Favorite",
    description:
      "The oldest covered market in Paris, 1615 — now a dozen kitchens under one iron roof.",
    detail:
      "Named for the red uniforms of the orphanage that once stood here. Moroccan, Japanese, Italian and Lebanese counters share communal tables; go before 1pm or expect to hover for a seat.",
    scores: {
      scenic: 6,
      hidden: 5,
      historic: 8,
      architecture: 4,
      nature: 1,
      food: 10,
      popularity: 7,
    },
    interests: ["food", "local", "historic", "cafes"],
    visitMinutes: 15,
    arrondissement: 3,
    neighborhood: "Haut Marais",
  },
  {
    id: "musee-carnavalet",
    name: "Musée Carnavalet",
    lat: 48.8573,
    lng: 2.3627,
    category: "Museum",
    kicker: "Historic Paris · Art & Galleries",
    description:
      "The history of Paris itself, in two Renaissance mansions with free permanent collections.",
    detail:
      "Shop signs, revolutionary relics, Proust's cork-lined bedroom. Even without going in, the twin courtyards and the orangery garden are worth the two-minute walk through.",
    scores: {
      scenic: 8,
      hidden: 4,
      historic: 10,
      architecture: 9,
      nature: 4,
      food: 2,
      popularity: 6,
    },
    interests: ["historic", "art", "architecture"],
    visitMinutes: 12,
    arrondissement: 3,
    neighborhood: "Le Marais",
  },
  {
    id: "rue-des-rosiers",
    name: "Rue des Rosiers",
    lat: 48.8571,
    lng: 2.3592,
    category: "Historic Street",
    kicker: "Food · Historic Paris",
    description:
      "The heart of the old Jewish quarter: bakeries, falafel counters and hand-painted signs.",
    detail:
      "A narrow street that has kept its trade for a century and a half — Sacha Finkelsztajn's yellow shopfront, the queue outside L'As du Fallafel, Hebrew lettering above doorways now shared with fashion boutiques.",
    scores: {
      scenic: 7,
      hidden: 4,
      historic: 9,
      architecture: 6,
      nature: 1,
      food: 9,
      popularity: 8,
    },
    interests: ["food", "historic", "local", "cafes"],
    visitMinutes: 10,
    arrondissement: 4,
    neighborhood: "Le Marais",
  },
  {
    id: "village-saint-paul",
    name: "Village Saint-Paul",
    lat: 48.8544,
    lng: 2.3609,
    category: "Courtyards",
    kicker: "Hidden Gem · Art & Galleries",
    description:
      "Five linked courtyards of antique dealers, tucked inside a medieval block.",
    detail:
      "Built into the grounds of the vanished Hôtel Saint-Pol. The courtyards connect by low archways and hold restorers, print dealers and a wine bar; a surviving stretch of Philippe Auguste's 12th-century city wall stands one street away.",
    scores: {
      scenic: 8,
      hidden: 9,
      historic: 9,
      architecture: 7,
      nature: 2,
      food: 4,
      popularity: 3,
    },
    interests: ["hidden", "art", "historic", "quiet", "local"],
    visitMinutes: 12,
    arrondissement: 4,
    neighborhood: "Saint-Paul",
  },
  {
    id: "rue-des-barres",
    name: "Rue des Barres",
    lat: 48.8552,
    lng: 2.3536,
    category: "Historic Street",
    kicker: "Hidden Gem · Historic Paris",
    description:
      "A quiet medieval-feeling street beside Saint-Gervais, a world away from the quai.",
    detail:
      "Cobbles, a stepped incline, half-timbered gables and the flying buttresses of Saint-Gervais overhead. One café puts tables out in good weather; otherwise you may have the street to yourself.",
    scores: {
      scenic: 9,
      hidden: 9,
      historic: 10,
      architecture: 8,
      nature: 1,
      food: 4,
      popularity: 3,
    },
    interests: ["hidden", "historic", "quiet", "romantic", "architecture"],
    visitMinutes: 5,
    arrondissement: 4,
    neighborhood: "Saint-Gervais",
  },
  {
    id: "saint-gervais",
    name: "Saint-Gervais-Saint-Protais",
    lat: 48.8556,
    lng: 2.3542,
    category: "Church",
    kicker: "Architecture · Historic Paris",
    description:
      "Flamboyant Gothic behind the first classical façade built in Paris.",
    detail:
      "The interior is dim, tall and usually silent apart from the monastic community that sings the offices here. The elm in the square outside marks the spot where justice was dispensed in the Middle Ages.",
    scores: {
      scenic: 8,
      hidden: 7,
      historic: 9,
      architecture: 9,
      nature: 2,
      food: 1,
      popularity: 4,
    },
    interests: ["architecture", "historic", "quiet", "hidden"],
    visitMinutes: 8,
    arrondissement: 4,
    neighborhood: "Saint-Gervais",
  },
  {
    id: "ile-saint-louis",
    name: "Île Saint-Louis",
    lat: 48.852,
    lng: 2.357,
    category: "Island",
    kicker: "Romantic · Iconic Paris",
    description:
      "A single 17th-century street down the spine of an island, with quays on both sides.",
    detail:
      "Laid out in one go in the 1660s and barely altered since. Rue Saint-Louis-en-l'Île runs the length of it; the quais below the plane trees are the best place in Paris to sit with an ice cream and watch the river work.",
    scores: {
      scenic: 10,
      hidden: 3,
      historic: 9,
      architecture: 9,
      nature: 6,
      food: 7,
      popularity: 9,
    },
    interests: ["romantic", "iconic", "historic", "architecture", "quiet"],
    visitMinutes: 12,
    arrondissement: 4,
    neighborhood: "Île Saint-Louis",
  },
  {
    id: "square-vert-galant",
    name: "Square du Vert-Galant",
    lat: 48.857,
    lng: 2.34,
    category: "Riverside Garden",
    kicker: "Romantic · Parks & Gardens",
    description:
      "The prow of the Île de la Cité, seven metres below the traffic and level with the Seine.",
    detail:
      "A willow, a few benches, and the river splitting around you. Named for Henri IV — the 'green gallant' — whose statue stands on the bridge above. The best free sunset in the 1st arrondissement.",
    scores: {
      scenic: 10,
      hidden: 6,
      historic: 8,
      architecture: 5,
      nature: 9,
      food: 1,
      popularity: 6,
    },
    interests: ["romantic", "parks", "quiet", "iconic"],
    visitMinutes: 10,
    arrondissement: 1,
    neighborhood: "Île de la Cité",
  },
  {
    id: "place-dauphine",
    name: "Place Dauphine",
    lat: 48.8564,
    lng: 2.3416,
    category: "Square",
    kicker: "Local Paris · Historic Paris",
    description:
      "A triangular tree-shaded square where the noise of the city simply stops.",
    detail:
      "Laid out in 1607, the second of Henri IV's royal squares. Boules under the chestnuts, two restaurants, and residents who have been here for decades. Yves Montand and Simone Signoret lived at number 15.",
    scores: {
      scenic: 9,
      hidden: 7,
      historic: 9,
      architecture: 8,
      nature: 6,
      food: 5,
      popularity: 5,
    },
    interests: ["quiet", "historic", "romantic", "architecture"],
    visitMinutes: 8,
    arrondissement: 1,
    neighborhood: "Île de la Cité",
  },
  {
    id: "cour-commerce",
    name: "Cour du Commerce Saint-André",
    lat: 48.8534,
    lng: 2.3392,
    category: "Historic Passage",
    kicker: "Hidden Gem · Cafés",
    description:
      "A cobbled 1776 alley where the guillotine was tested and the first Paris café still trades.",
    detail:
      "Marat printed L'Ami du Peuple at number 8; Doctor Guillotin tried his machine on sheep next door. Le Procope, opened 1686, backs onto the passage. A tower of Philippe Auguste's wall is visible through a window at number 4.",
    scores: {
      scenic: 9,
      hidden: 8,
      historic: 10,
      architecture: 7,
      nature: 1,
      food: 7,
      popularity: 5,
    },
    interests: ["hidden", "historic", "cafes", "architecture"],
    visitMinutes: 7,
    arrondissement: 6,
    neighborhood: "Odéon",
  },
  {
    id: "shakespeare-company",
    name: "Shakespeare and Company",
    lat: 48.8526,
    lng: 2.347,
    category: "Bookshop",
    kicker: "Bookshops · Iconic Paris",
    description:
      "The English-language bookshop facing Notre-Dame, with beds between the shelves.",
    detail:
      "George Whitman's 1951 shop, heir to Sylvia Beach's name. Writers still sleep upstairs in exchange for a few hours' work. Upstairs there is a piano, a typewriter and a reading room nobody will hurry you out of.",
    scores: {
      scenic: 8,
      hidden: 2,
      historic: 7,
      architecture: 5,
      nature: 1,
      food: 4,
      popularity: 9,
    },
    interests: ["bookshops", "iconic", "cafes", "romantic"],
    visitMinutes: 12,
    arrondissement: 5,
    neighborhood: "Latin Quarter",
  },
  {
    id: "jardin-luxembourg",
    name: "Jardin du Luxembourg",
    lat: 48.8462,
    lng: 2.3372,
    category: "Garden",
    kicker: "Parks & Gardens · Iconic Paris",
    description:
      "Twenty-three hectares of gravel, green chairs and toy sailboats on a round basin.",
    detail:
      "Marie de Médicis' garden of 1612, half formal French, half English. The Medici Fountain in its shaded alley is the most romantic corner; the orchard at the south-west holds hundreds of heritage apple varieties.",
    scores: {
      scenic: 10,
      hidden: 1,
      historic: 9,
      architecture: 7,
      nature: 10,
      food: 3,
      popularity: 10,
    },
    interests: ["parks", "iconic", "romantic", "quiet"],
    visitMinutes: 20,
    arrondissement: 6,
    neighborhood: "Odéon",
  },
  {
    id: "rue-mouffetard",
    name: "Rue Mouffetard",
    lat: 48.8425,
    lng: 2.3495,
    category: "Market Street",
    kicker: "Food · Local Favorite",
    description:
      "A Roman road turned market street, tumbling downhill past cheese shops and student bars.",
    detail:
      "One of the oldest streets in Paris and still a working market at the bottom end. Hemingway lived at number 74 on the neighbouring rue du Cardinal Lemoine and called this 'a wonderful narrow crowded market street'.",
    scores: {
      scenic: 8,
      hidden: 3,
      historic: 9,
      architecture: 6,
      nature: 1,
      food: 10,
      popularity: 8,
    },
    interests: ["food", "local", "historic", "cafes"],
    visitMinutes: 15,
    arrondissement: 5,
    neighborhood: "Mouffetard",
  },
  {
    id: "arenes-lutece",
    name: "Arènes de Lutèce",
    lat: 48.8452,
    lng: 2.3527,
    category: "Roman Ruin",
    kicker: "Hidden Gem · Historic Paris",
    description:
      "A 1st-century Roman amphitheatre, entered through a doorway on an ordinary street.",
    detail:
      "Lost for centuries, rediscovered in 1869 when a tram depot was dug. It seated 15,000; today old men play boules on the arena floor and children run the tiers. There is no sign worth the name outside.",
    scores: {
      scenic: 7,
      hidden: 10,
      historic: 10,
      architecture: 7,
      nature: 6,
      food: 1,
      popularity: 4,
    },
    interests: ["hidden", "historic", "quiet", "parks"],
    visitMinutes: 10,
    arrondissement: 5,
    neighborhood: "Latin Quarter",
  },
  {
    id: "canal-saint-martin",
    name: "Canal Saint-Martin",
    lat: 48.871,
    lng: 2.3665,
    category: "Canal",
    kicker: "Local Favorite · Romantic",
    description:
      "Iron footbridges, plane trees and locks — the city's most unhurried waterway.",
    detail:
      "Napoleon's canal of 1802, now the spine of a neighbourhood of small bars and design shops. Sit on the quai with something from a nearby épicerie and watch a barge take twenty minutes to drop through a lock.",
    scores: {
      scenic: 9,
      hidden: 4,
      historic: 7,
      architecture: 5,
      nature: 8,
      food: 8,
      popularity: 7,
    },
    interests: ["local", "romantic", "cafes", "parks", "quiet"],
    visitMinutes: 15,
    arrondissement: 10,
    neighborhood: "Canal Saint-Martin",
  },
  {
    id: "jardin-tuileries",
    name: "Jardin des Tuileries",
    lat: 48.8635,
    lng: 2.3272,
    category: "Garden",
    kicker: "Iconic Paris · Parks & Gardens",
    description:
      "Le Nôtre's grand axis of gravel, statuary and round ponds between the Louvre and Concorde.",
    detail:
      "The blueprint for the formal French garden, opened to the public in 1667. Pull a green chair to the edge of the octagonal basin and you have the best seat on the Right Bank.",
    scores: {
      scenic: 9,
      hidden: 1,
      historic: 9,
      architecture: 7,
      nature: 9,
      food: 3,
      popularity: 10,
    },
    interests: ["parks", "iconic", "romantic", "art"],
    visitMinutes: 15,
    arrondissement: 1,
    neighborhood: "Tuileries",
  },
  {
    id: "pont-des-arts",
    name: "Pont des Arts",
    lat: 48.8583,
    lng: 2.3374,
    category: "Bridge",
    kicker: "Romantic · Iconic Paris",
    description:
      "A wooden-decked pedestrian bridge with the best framed view of the Île de la Cité.",
    detail:
      "The first iron bridge in Paris, rebuilt in 1984 and now free of its padlocks. Artists work along the deck; at dusk the light down the river towards the Pont Neuf is the reason people move here.",
    scores: {
      scenic: 10,
      hidden: 2,
      historic: 7,
      architecture: 7,
      nature: 5,
      food: 1,
      popularity: 9,
    },
    interests: ["romantic", "iconic", "art"],
    visitMinutes: 6,
    arrondissement: 6,
    neighborhood: "Saint-Germain",
  },
  {
    id: "cour-rohan",
    name: "Cour de Rohan",
    lat: 48.8531,
    lng: 2.3383,
    category: "Courtyards",
    kicker: "Hidden Gem · Historic Paris",
    description:
      "Three linked private courtyards with a surviving Renaissance mounting block.",
    detail:
      "Off the Cour du Commerce, gated but usually open in the daytime. Wisteria, a well, and the last 'pas-de-mule' in Paris — the stone step noblewomen used to climb onto their mules.",
    scores: {
      scenic: 9,
      hidden: 10,
      historic: 9,
      architecture: 8,
      nature: 4,
      food: 1,
      popularity: 2,
    },
    interests: ["hidden", "quiet", "historic", "architecture", "romantic"],
    visitMinutes: 5,
    arrondissement: 6,
    neighborhood: "Odéon",
  },
  {
    id: "place-du-marche-sainte-catherine",
    name: "Place du Marché Sainte-Catherine",
    lat: 48.8558,
    lng: 2.3634,
    category: "Square",
    kicker: "Cafés · Local Paris",
    description:
      "A small tree-filled square of terraces, hidden one street off the rue Saint-Antoine.",
    detail:
      "Built on the site of a priory and pedestrianised long before the rest of the Marais. Four or five restaurants put tables under the trees; in the evening it feels like a village square that lost its village.",
    scores: {
      scenic: 8,
      hidden: 8,
      historic: 7,
      architecture: 6,
      nature: 6,
      food: 8,
      popularity: 4,
    },
    interests: ["cafes", "quiet", "romantic", "local", "food"],
    visitMinutes: 8,
    arrondissement: 4,
    neighborhood: "Le Marais",
  },
  {
    id: "fontaine-stravinsky",
    name: "Fontaine Stravinsky",
    lat: 48.859,
    lng: 2.3512,
    category: "Fountain",
    kicker: "Art & Galleries · Iconic Paris",
    description:
      "Sixteen mechanical sculptures spitting water beside the Centre Pompidou.",
    detail:
      "Niki de Saint Phalle's colours against Jean Tinguely's black machines, 1983. Loud, absurd and entirely un-Parisian, which is the point. The terraces on the south side get the afternoon sun.",
    scores: {
      scenic: 7,
      hidden: 3,
      historic: 4,
      architecture: 6,
      nature: 3,
      food: 6,
      popularity: 8,
    },
    interests: ["art", "iconic", "cafes"],
    visitMinutes: 6,
    arrondissement: 4,
    neighborhood: "Beaubourg",
  },
  {
    id: "galerie-vero-dodat",
    name: "Galerie Véro-Dodat",
    lat: 48.8624,
    lng: 2.3406,
    category: "Historic Passage",
    kicker: "Hidden Gem · Architecture",
    description:
      "Black-and-white tiled floors, mahogany shopfronts and brass — the most theatrical arcade.",
    detail:
      "Opened 1826 by two charcutiers, restored to its neoclassical gloom. Luthiers and a couture house share it now, and it is almost always empty enough to hear your own footsteps.",
    scores: {
      scenic: 9,
      hidden: 9,
      historic: 9,
      architecture: 10,
      nature: 1,
      food: 3,
      popularity: 3,
    },
    interests: ["hidden", "architecture", "historic", "quiet", "art"],
    visitMinutes: 6,
    arrondissement: 1,
    neighborhood: "Louvre",
  },
  {
    id: "rue-de-furstemberg",
    name: "Place de Furstemberg",
    lat: 48.8541,
    lng: 2.3345,
    category: "Square",
    kicker: "Romantic · Hidden Gem",
    description:
      "Four paulownia trees and a white globe lamp — reputedly the most romantic square in Paris.",
    detail:
      "Delacroix kept his studio and garden off this square; it is now a small museum. The paulownias flower purple in late April and the square is lit at night like a stage set.",
    scores: {
      scenic: 10,
      hidden: 8,
      historic: 8,
      architecture: 8,
      nature: 6,
      food: 2,
      popularity: 4,
    },
    interests: ["romantic", "quiet", "hidden", "art", "architecture"],
    visitMinutes: 6,
    arrondissement: 6,
    neighborhood: "Saint-Germain",
  },
  {
    id: "passage-verdeau",
    name: "Passage Verdeau",
    lat: 48.8735,
    lng: 2.3437,
    category: "Historic Passage",
    kicker: "Bookshops · Hidden Gem",
    description:
      "Old photographs, prints and antiquarian books under a fishbone glass roof.",
    detail:
      "The quietest of the linked northern passages. Dealers in vintage cameras and 19th-century engravings; the light through the roof at midday is worth the detour on its own.",
    scores: {
      scenic: 8,
      hidden: 9,
      historic: 8,
      architecture: 8,
      nature: 1,
      food: 3,
      popularity: 3,
    },
    interests: ["bookshops", "hidden", "architecture", "historic", "quiet"],
    visitMinutes: 7,
    arrondissement: 9,
    neighborhood: "Grands Boulevards",
  },
  {
    id: "quai-de-bourbon",
    name: "Quai de Bourbon",
    lat: 48.8541,
    lng: 2.3593,
    category: "Riverside",
    kicker: "Architecture · Romantic",
    description:
      "The northern quay of Île Saint-Louis, with steps down to the water's edge.",
    detail:
      "Camille Claudel worked at number 19. From the tip of the island you look straight at the flying buttresses of Notre-Dame across the smaller arm of the Seine.",
    scores: {
      scenic: 10,
      hidden: 6,
      historic: 8,
      architecture: 8,
      nature: 7,
      food: 2,
      popularity: 6,
    },
    interests: ["quiet", "romantic", "architecture", "iconic"],
    visitMinutes: 8,
    arrondissement: 4,
    neighborhood: "Île Saint-Louis",
  },
  {
    id: "musee-rodin",
    name: "Musée Rodin",
    lat: 48.8553,
    lng: 2.3158,
    category: "Museum",
    kicker: "Art & Galleries · Garden",
    description:
      "Rodin's sculpture collection inhabits an 18th-century mansion and its planted grounds.",
    detail:
      "The museum occupies the Hôtel Biron, where Rodin worked during the final years of his life. Bronze figures punctuate the garden, giving the site an outdoor presence as well as a museum interior.",
    scores: {
      scenic: 9,
      hidden: 3,
      historic: 8,
      architecture: 8,
      nature: 8,
      food: 1,
      popularity: 8,
    },
    interests: ["art", "parks", "architecture", "historic", "romantic"],
    visitMinutes: 20,
    arrondissement: 7,
    neighborhood: "Invalides",
  },
  {
    id: "hotel-des-invalides",
    name: "Hôtel des Invalides",
    lat: 48.8569,
    lng: 2.3128,
    category: "Palace & Courtyard",
    kicker: "Architecture · Historic Paris",
    description:
      "A vast veterans' complex organized around formal courtyards and the gilded Dôme church.",
    detail:
      "Louis XIV founded the institution for wounded and elderly soldiers. Its long classical façade and axial courtyards lead toward the dome designed by Jules Hardouin-Mansart.",
    scores: {
      scenic: 9,
      hidden: 1,
      historic: 10,
      architecture: 10,
      nature: 4,
      food: 1,
      popularity: 9,
    },
    interests: ["architecture", "historic", "iconic"],
    visitMinutes: 15,
    arrondissement: 7,
    neighborhood: "Invalides",
  },
  {
    id: "rue-cler",
    name: "Rue Cler",
    lat: 48.8584,
    lng: 2.3053,
    category: "Market Street",
    kicker: "Local Favorite · Food",
    description: "A compact market street lined with greengrocers, food shops and café terraces.",
    detail:
      "The pedestrian-priority section concentrates everyday food shopping into a few lively blocks. Its western location adds a neighborhood-scale discovery between Invalides and the Eiffel Tower corridors.",
    scores: {
      scenic: 6,
      hidden: 3,
      historic: 4,
      architecture: 4,
      nature: 2,
      food: 9,
      popularity: 7,
    },
    interests: ["food", "cafes", "local"],
    visitMinutes: 10,
    arrondissement: 7,
    neighborhood: "Gros-Caillou",
  },
  {
    id: "champ-de-mars",
    name: "Champ de Mars",
    lat: 48.8556,
    lng: 2.2987,
    category: "Garden",
    kicker: "Parks & Gardens · Iconic Paris",
    description: "A long public garden framing the Eiffel Tower from the École Militaire axis.",
    detail:
      "The former military exercise ground became a setting for major exhibitions before settling into its present garden form. This anchor marks a public path near the southern end rather than the center of the lawns.",
    scores: {
      scenic: 9,
      hidden: 1,
      historic: 7,
      architecture: 4,
      nature: 8,
      food: 1,
      popularity: 10,
    },
    interests: ["parks", "iconic", "romantic", "historic"],
    visitMinutes: 12,
    arrondissement: 7,
    neighborhood: "Gros-Caillou",
  },
  {
    id: "ecole-militaire",
    name: "École Militaire",
    lat: 48.8525,
    lng: 2.3047,
    category: "Palace & Courtyard",
    kicker: "Architecture · Historic Paris",
    description:
      "An 18th-century military academy closing the southern vista of the Champ de Mars.",
    detail:
      "Founded under Louis XV, the school was designed as a monumental training institution for officers. Its domed central pavilion is best encountered from the public forecourt and garden axis.",
    scores: {
      scenic: 8,
      hidden: 2,
      historic: 9,
      architecture: 9,
      nature: 3,
      food: 1,
      popularity: 7,
    },
    interests: ["architecture", "historic", "iconic"],
    visitMinutes: 7,
    arrondissement: 7,
    neighborhood: "École Militaire",
  },
  {
    id: "pont-alexandre-iii",
    name: "Pont Alexandre III",
    lat: 48.8637,
    lng: 2.3136,
    category: "Bridge",
    kicker: "Architecture · Romantic",
    description:
      "An exuberant Beaux-Arts bridge marked by gilded statues, lamps and a low Seine arch.",
    detail:
      "Built for the 1900 Exposition Universelle, the bridge links the Invalides axis to the Grand and Petit Palais. Its ornament was carefully arranged without blocking the long views on either bank.",
    scores: {
      scenic: 10,
      hidden: 1,
      historic: 8,
      architecture: 10,
      nature: 6,
      food: 1,
      popularity: 9,
    },
    interests: ["architecture", "historic", "romantic", "iconic"],
    visitMinutes: 8,
    arrondissement: 7,
    neighborhood: "Invalides",
  },
  {
    id: "jardin-catherine-laboure",
    name: "Jardin Catherine-Labouré",
    lat: 48.8505,
    lng: 2.3197,
    category: "Garden",
    kicker: "Hidden Gem · Parks & Gardens",
    description: "A former convent kitchen garden tucked behind a long wall on rue de Babylone.",
    detail:
      "Fruit trees, vines and vegetable plots preserve the site's productive-garden character. The public gate on rue de Babylone is the meaningful anchor for this unusually concealed green space.",
    scores: {
      scenic: 8,
      hidden: 9,
      historic: 6,
      architecture: 3,
      nature: 10,
      food: 2,
      popularity: 3,
    },
    interests: ["hidden", "parks", "quiet", "local"],
    visitMinutes: 10,
    arrondissement: 7,
    neighborhood: "Saint-Thomas-d'Aquin",
  },
  {
    id: "musee-quai-branly",
    name: "Musée du quai Branly – Jacques Chirac",
    lat: 48.8607,
    lng: 2.2977,
    category: "Museum",
    kicker: "Art & Galleries · Architecture",
    description:
      "Jean Nouvel's museum sits behind a planted garden and a distinctive living-wall façade.",
    detail:
      "The institution presents arts and cultures from Africa, Asia, Oceania and the Americas. Its public-facing garden edge and glass screen make the Quai Branly entrance a useful pedestrian encounter even without a museum visit.",
    scores: {
      scenic: 8,
      hidden: 3,
      historic: 4,
      architecture: 9,
      nature: 8,
      food: 1,
      popularity: 8,
    },
    interests: ["art", "architecture", "parks", "iconic"],
    visitMinutes: 15,
    arrondissement: 7,
    neighborhood: "Gros-Caillou",
  },
  {
    id: "petit-palais",
    name: "Petit Palais",
    lat: 48.866,
    lng: 2.3146,
    category: "Museum",
    kicker: "Art & Galleries · Architecture",
    description: "A 1900 exhibition palace wrapping a semicircular garden courtyard.",
    detail:
      "Charles Girault designed the building for the Exposition Universelle, pairing a monumental entrance with mosaics, sculpture and ironwork. It now houses the City of Paris Museum of Fine Arts.",
    scores: {
      scenic: 9,
      hidden: 3,
      historic: 8,
      architecture: 10,
      nature: 5,
      food: 2,
      popularity: 8,
    },
    interests: ["art", "architecture", "historic", "romantic"],
    visitMinutes: 15,
    arrondissement: 8,
    neighborhood: "Champs-Élysées",
  },
  {
    id: "grand-palais",
    name: "Grand Palais",
    lat: 48.8661,
    lng: 2.3125,
    category: "Museum",
    kicker: "Architecture · Iconic Paris",
    description: "A monumental stone façade concealing one of Paris's great glass-and-steel roofs.",
    detail:
      "Created for the 1900 Exposition Universelle, the building combines classical masonry with an immense iron nave. The Avenue Winston-Churchill forecourt provides a clear public view of its sculpture and colonnade.",
    scores: {
      scenic: 9,
      hidden: 1,
      historic: 8,
      architecture: 10,
      nature: 2,
      food: 1,
      popularity: 9,
    },
    interests: ["architecture", "historic", "art", "iconic"],
    visitMinutes: 10,
    arrondissement: 8,
    neighborhood: "Champs-Élysées",
  },
  {
    id: "place-de-la-concorde",
    name: "Place de la Concorde",
    lat: 48.8656,
    lng: 2.3212,
    category: "Square",
    kicker: "Historic Paris · Iconic Paris",
    description: "A vast royal square transformed by revolution and centered on the Luxor Obelisk.",
    detail:
      "Designed in the 18th century, the square later became a principal site of Revolutionary executions. Its fountains, statues and long axes connect the Tuileries, Champs-Élysées and Madeleine.",
    scores: {
      scenic: 9,
      hidden: 0,
      historic: 10,
      architecture: 9,
      nature: 3,
      food: 1,
      popularity: 10,
    },
    interests: ["historic", "architecture", "iconic"],
    visitMinutes: 8,
    arrondissement: 8,
    neighborhood: "Concorde",
  },
  {
    id: "parc-monceau",
    name: "Parc Monceau",
    lat: 48.8796,
    lng: 2.3089,
    category: "Garden",
    kicker: "Parks & Gardens · Romantic",
    description:
      "A landscaped park of curving paths, mature trees and deliberately theatrical ruins.",
    detail:
      "The garden evolved from an 18th-century picturesque folly into a public park under the Second Empire. A classical rotunda announces the main Boulevard de Courcelles entrance used as this anchor.",
    scores: {
      scenic: 9,
      hidden: 4,
      historic: 7,
      architecture: 5,
      nature: 10,
      food: 1,
      popularity: 8,
    },
    interests: ["parks", "romantic", "local", "historic"],
    visitMinutes: 12,
    arrondissement: 8,
    neighborhood: "Europe",
  },
  {
    id: "eglise-de-la-madeleine",
    name: "Église de la Madeleine",
    lat: 48.87,
    lng: 2.3244,
    category: "Church",
    kicker: "Architecture · Historic Paris",
    description:
      "A church conceived as a Roman temple, encircled by a monumental Corinthian colonnade.",
    detail:
      "Its long and politically complicated construction crossed the Revolution and Napoleonic era. The broad southern steps face directly down rue Royale toward Place de la Concorde.",
    scores: {
      scenic: 8,
      hidden: 1,
      historic: 9,
      architecture: 10,
      nature: 1,
      food: 3,
      popularity: 8,
    },
    interests: ["architecture", "historic", "iconic"],
    visitMinutes: 9,
    arrondissement: 8,
    neighborhood: "Madeleine",
  },
  {
    id: "chapelle-expiatoire",
    name: "Chapelle Expiatoire",
    lat: 48.8736,
    lng: 2.3228,
    category: "Church",
    kicker: "Hidden Gem · Historic Paris",
    description:
      "A neoclassical memorial chapel secluded within a planted square near Saint-Lazare.",
    detail:
      "The Restoration-era monument stands on part of the former Madeleine Cemetery, where Louis XVI and Marie Antoinette were initially buried. Its walled precinct makes an unexpectedly sheltered fragment of royal memory.",
    scores: {
      scenic: 7,
      hidden: 8,
      historic: 10,
      architecture: 8,
      nature: 5,
      food: 1,
      popularity: 3,
    },
    interests: ["hidden", "historic", "architecture", "quiet"],
    visitMinutes: 8,
    arrondissement: 8,
    neighborhood: "Madeleine",
  },
  {
    id: "musee-jacquemart-andre",
    name: "Musée Jacquemart-André",
    lat: 48.8755,
    lng: 2.3105,
    category: "Mansion",
    kicker: "Art & Galleries · Architecture",
    description:
      "A grand private mansion preserving the collection and interiors of an art-collecting couple.",
    detail:
      "Édouard André and Nélie Jacquemart assembled paintings, sculpture and decorative arts within their Boulevard Haussmann home. The raised forecourt gives pedestrians a strong view of the mansion's formal entrance.",
    scores: {
      scenic: 8,
      hidden: 4,
      historic: 7,
      architecture: 9,
      nature: 2,
      food: 3,
      popularity: 7,
    },
    interests: ["art", "architecture", "historic"],
    visitMinutes: 12,
    arrondissement: 8,
    neighborhood: "Faubourg-du-Roule",
  },
  {
    id: "pont-de-lalma",
    name: "Pont de l'Alma",
    lat: 48.8644,
    lng: 2.3013,
    category: "Bridge",
    kicker: "Riverside · Local Landmark",
    description:
      "A Seine crossing known for the Zouave statue long used by Parisians to gauge floods.",
    detail:
      "The present bridge replaced a 19th-century structure but retained the stone Zouave at its upstream pier. The right-bank approach also opens broad views toward the Eiffel Tower and Quai Branly.",
    scores: {
      scenic: 7,
      hidden: 3,
      historic: 7,
      architecture: 5,
      nature: 6,
      food: 1,
      popularity: 7,
    },
    interests: ["historic", "local", "iconic"],
    visitMinutes: 6,
    arrondissement: 8,
    neighborhood: "Alma-Marceau",
  },
  {
    id: "pantheon",
    name: "Panthéon",
    lat: 48.8462,
    lng: 2.346,
    category: "Museum",
    kicker: "Architecture · Historic Paris",
    description: "A domed neoclassical monument crowning the Montagne Sainte-Geneviève.",
    detail:
      "Begun as a church dedicated to Saint Geneviève, the building became a national mausoleum during the Revolution. Its columned portico terminates one of the Latin Quarter's clearest urban vistas.",
    scores: {
      scenic: 9,
      hidden: 0,
      historic: 10,
      architecture: 10,
      nature: 1,
      food: 1,
      popularity: 9,
    },
    interests: ["architecture", "historic", "iconic"],
    visitMinutes: 10,
    arrondissement: 5,
    neighborhood: "Sorbonne",
  },
  {
    id: "musee-de-cluny",
    name: "Musée de Cluny",
    lat: 48.8506,
    lng: 2.3431,
    category: "Museum",
    kicker: "Historic Paris · Art & Galleries",
    description: "A medieval mansion joined to the surviving Roman baths of ancient Lutetia.",
    detail:
      "The museum occupies the Hôtel des Abbés de Cluny beside the Gallo-Roman thermal complex. Its street-facing masonry layers medieval Paris against one of the city's most substantial ancient remains.",
    scores: {
      scenic: 8,
      hidden: 4,
      historic: 10,
      architecture: 9,
      nature: 3,
      food: 1,
      popularity: 7,
    },
    interests: ["historic", "architecture", "art"],
    visitMinutes: 12,
    arrondissement: 5,
    neighborhood: "Latin Quarter",
  },
  {
    id: "college-des-bernardins",
    name: "Collège des Bernardins",
    lat: 48.8489,
    lng: 2.3524,
    category: "Church",
    kicker: "Hidden Gem · Architecture",
    description:
      "A restored medieval Cistercian college with a long, rib-vaulted former refectory.",
    detail:
      "Founded in the 13th century for monks studying in Paris, the complex survived changing institutional uses. The public entrance on rue de Poissy reveals an austere Gothic interior just off the Seine corridors.",
    scores: {
      scenic: 8,
      hidden: 8,
      historic: 9,
      architecture: 9,
      nature: 1,
      food: 1,
      popularity: 4,
    },
    interests: ["hidden", "historic", "architecture", "quiet"],
    visitMinutes: 8,
    arrondissement: 5,
    neighborhood: "Maubert",
  },
  {
    id: "jardin-des-plantes",
    name: "Jardin des Plantes",
    lat: 48.843,
    lng: 2.3597,
    category: "Garden",
    kicker: "Parks & Gardens · Historic Paris",
    description:
      "The national natural-history garden combines formal beds, botany and a long plane-tree promenade.",
    detail:
      "Its origins lie in the royal medicinal-plant garden created in the 17th century. This anchor uses the public Place Valhubert entrance at the eastern end of the main garden axis.",
    scores: {
      scenic: 8,
      hidden: 2,
      historic: 8,
      architecture: 4,
      nature: 10,
      food: 1,
      popularity: 8,
    },
    interests: ["parks", "historic", "local"],
    visitMinutes: 15,
    arrondissement: 5,
    neighborhood: "Jardin-des-Plantes",
  },
  {
    id: "eglise-saint-sulpice",
    name: "Église Saint-Sulpice",
    lat: 48.8512,
    lng: 2.3346,
    category: "Church",
    kicker: "Architecture · Historic Paris",
    description:
      "A monumental church with an asymmetrical west front facing a fountain-lined square.",
    detail:
      "Most of the present church dates from the 17th and 18th centuries. Inside are murals by Delacroix and the meridian line associated with its historic astronomical gnomon.",
    scores: {
      scenic: 8,
      hidden: 2,
      historic: 9,
      architecture: 9,
      nature: 2,
      food: 1,
      popularity: 8,
    },
    interests: ["architecture", "historic", "art", "iconic"],
    visitMinutes: 10,
    arrondissement: 6,
    neighborhood: "Odéon",
  },
  {
    id: "musee-eugene-delacroix",
    name: "Musée national Eugène-Delacroix",
    lat: 48.854,
    lng: 2.3356,
    category: "Museum",
    kicker: "Art & Galleries · Hidden Gem",
    description:
      "Delacroix's final apartment and studio open onto a secluded garden off Place de Fürstenberg.",
    detail:
      "The painter moved here to work near Saint-Sulpice, where he was decorating a chapel. The small museum preserves an intimate link between the square, studio and private garden.",
    scores: {
      scenic: 8,
      hidden: 8,
      historic: 8,
      architecture: 6,
      nature: 6,
      food: 1,
      popularity: 5,
    },
    interests: ["art", "hidden", "historic", "quiet", "romantic"],
    visitMinutes: 9,
    arrondissement: 6,
    neighborhood: "Saint-Germain-des-Prés",
  },
  {
    id: "institut-de-france",
    name: "Institut de France",
    lat: 48.8573,
    lng: 2.3364,
    category: "Palace & Courtyard",
    kicker: "Architecture · Historic Paris",
    description:
      "A domed 17th-century college forming the Left Bank terminus of the Pont des Arts.",
    detail:
      "The building was founded through Cardinal Mazarin's bequest and later became the seat of the Institut de France. Its curved façade and cupola close the bridge vista from the Louvre.",
    scores: {
      scenic: 8,
      hidden: 2,
      historic: 9,
      architecture: 9,
      nature: 2,
      food: 1,
      popularity: 7,
    },
    interests: ["architecture", "historic", "iconic"],
    visitMinutes: 6,
    arrondissement: 6,
    neighborhood: "Saint-Germain-des-Prés",
  },
  {
    id: "ecume-des-pages",
    name: "L'Écume des Pages",
    lat: 48.8544,
    lng: 2.3325,
    category: "Bookshop",
    kicker: "Bookshops · Local Favorite",
    description: "A long-established independent general bookshop on Boulevard Saint-Germain.",
    detail:
      "Its broad literary selection sustains the bookselling identity of Saint-Germain beyond the neighborhood's famous cafés. The street-level storefront makes it an easy public-facing discovery.",
    scores: {
      scenic: 5,
      hidden: 4,
      historic: 5,
      architecture: 3,
      nature: 0,
      food: 2,
      popularity: 6,
    },
    interests: ["bookshops", "local", "cafes"],
    visitMinutes: 8,
    arrondissement: 6,
    neighborhood: "Saint-Germain-des-Prés",
  },
  {
    id: "sainte-chapelle",
    name: "Sainte-Chapelle",
    lat: 48.8554,
    lng: 2.345,
    category: "Church",
    kicker: "Architecture · Iconic Paris",
    description: "A royal Gothic chapel whose upper walls dissolve into towering stained glass.",
    detail:
      "Louis IX commissioned the chapel within the medieval royal palace to house sacred relics. Its exterior spire and stonework remain legible from public approaches around the Palais de Justice.",
    scores: {
      scenic: 10,
      hidden: 1,
      historic: 10,
      architecture: 10,
      nature: 1,
      food: 0,
      popularity: 10,
    },
    interests: ["architecture", "historic", "art", "iconic"],
    visitMinutes: 10,
    arrondissement: 1,
    neighborhood: "Île de la Cité",
  },
  {
    id: "musee-orangerie",
    name: "Musée de l'Orangerie",
    lat: 48.8638,
    lng: 2.3226,
    category: "Museum",
    kicker: "Art & Galleries · Parks & Gardens",
    description: "A former Tuileries orangery adapted around Monet's panoramic Water Lilies.",
    detail:
      "The building stands at the garden's western terrace overlooking Place de la Concorde. Its purpose-built oval rooms give the large paintings a continuous, enveloping setting.",
    scores: {
      scenic: 8,
      hidden: 2,
      historic: 7,
      architecture: 6,
      nature: 6,
      food: 1,
      popularity: 9,
    },
    interests: ["art", "parks", "iconic", "romantic"],
    visitMinutes: 12,
    arrondissement: 1,
    neighborhood: "Tuileries",
  },
  {
    id: "bnf-richelieu",
    name: "Bibliothèque nationale de France – Richelieu",
    lat: 48.8682,
    lng: 2.3385,
    category: "Museum",
    kicker: "Bookshops · Architecture",
    description:
      "France's historic national-library site combines a grand reading room, museum and public passage.",
    detail:
      "The Richelieu quadrangle grew across several centuries around the former royal collections. The rue Vivienne entrance leads toward the oval reading room and extends the nearby covered-passage corridor.",
    scores: {
      scenic: 8,
      hidden: 5,
      historic: 9,
      architecture: 9,
      nature: 1,
      food: 1,
      popularity: 7,
    },
    interests: ["bookshops", "architecture", "historic", "art", "quiet"],
    visitMinutes: 10,
    arrondissement: 2,
    neighborhood: "Richelieu",
  },
  {
    id: "tour-jean-sans-peur",
    name: "Tour Jean-sans-Peur",
    lat: 48.8645,
    lng: 2.3484,
    category: "Mansion",
    kicker: "Hidden Gem · Historic Paris",
    description:
      "A rare medieval residential tower embedded in the street wall near Étienne Marcel.",
    detail:
      "The tower is the principal surviving fragment of the Dukes of Burgundy's Paris residence. Its fortified exterior and elaborate stone staircase preserve an unusually tangible piece of medieval domestic architecture.",
    scores: {
      scenic: 7,
      hidden: 8,
      historic: 10,
      architecture: 8,
      nature: 0,
      food: 1,
      popularity: 4,
    },
    interests: ["hidden", "historic", "architecture"],
    visitMinutes: 7,
    arrondissement: 2,
    neighborhood: "Montorgueil",
  },
  {
    id: "square-du-temple",
    name: "Square du Temple – Elie-Wiesel",
    lat: 48.8648,
    lng: 2.3604,
    category: "Garden",
    kicker: "Parks & Gardens · Local Paris",
    description: "A landscaped neighborhood garden on the former precinct of the Knights Templar.",
    detail:
      "Created during the Second Empire, the square includes mature trees, a pond and gently winding paths. Its public gate on rue de Bretagne adds green coverage beside the market corridors of the northern Marais.",
    scores: {
      scenic: 7,
      hidden: 4,
      historic: 7,
      architecture: 3,
      nature: 9,
      food: 3,
      popularity: 6,
    },
    interests: ["parks", "local", "historic"],
    visitMinutes: 9,
    arrondissement: 3,
    neighborhood: "Temple",
  },
  {
    id: "musee-picasso-paris",
    name: "Musée national Picasso-Paris",
    lat: 48.8599,
    lng: 2.3622,
    category: "Mansion",
    kicker: "Art & Galleries · Architecture",
    description: "Picasso's works fill the sculpted rooms of the 17th-century Hôtel Salé.",
    detail:
      "The mansion takes its name from the salt-tax official who commissioned it. Its grand staircase and courtyard architecture give the collection a strong historic setting in the eastern Marais.",
    scores: {
      scenic: 8,
      hidden: 3,
      historic: 8,
      architecture: 9,
      nature: 2,
      food: 1,
      popularity: 8,
    },
    interests: ["art", "architecture", "historic"],
    visitMinutes: 12,
    arrondissement: 3,
    neighborhood: "Le Marais",
  },
  {
    id: "hotel-de-sens",
    name: "Hôtel de Sens",
    lat: 48.8533,
    lng: 2.3589,
    category: "Mansion",
    kicker: "Architecture · Hidden Gem",
    description: "A turreted late-medieval mansion now housing the Forney decorative-arts library.",
    detail:
      "Built for the archbishops of Sens around the turn of the 16th century, it is one of the Marais's rare surviving medieval residences. The public street corner clearly reveals its towers, gate and formal garden edge.",
    scores: {
      scenic: 9,
      hidden: 6,
      historic: 10,
      architecture: 10,
      nature: 4,
      food: 1,
      popularity: 6,
    },
    interests: ["architecture", "historic", "hidden", "bookshops"],
    visitMinutes: 8,
    arrondissement: 4,
    neighborhood: "Saint-Paul",
  },
  {
    id: "memorial-de-la-shoah",
    name: "Mémorial de la Shoah",
    lat: 48.8547,
    lng: 2.3561,
    category: "Museum",
    kicker: "Historic Paris · Memorial",
    description:
      "A research, education and remembrance site centered on the history of the Holocaust in France.",
    detail:
      "The forecourt's Wall of the Righteous and the interior Wall of Names frame a sober place of memory. This is a historically significant discovery rather than a conventional scenic stop and should be approached respectfully.",
    scores: {
      scenic: 4,
      hidden: 4,
      historic: 10,
      architecture: 5,
      nature: 1,
      food: 0,
      popularity: 6,
    },
    interests: ["historic", "local"],
    visitMinutes: 10,
    arrondissement: 4,
    neighborhood: "Le Marais",
  },
];

assertValidPoiDataset(CURATED_POIS);

export const POIS = CURATED_POIS;

export const poiById = (id: string) => POIS.find((p) => p.id === id);
