import type { Poi } from "./types";
import { assertValidPoiDataset } from "./poi-validation";

/**
 * Seeded central-Paris POI dataset.
 * MOCK DATA LAYER — see ./services.ts. Swap for Overpass / Wikidata / OpenTripMap
 * without touching the routing engine or UI.
 */
const CURATED_POIS: Poi[] = [
  {
    id: "palais-royal",
    name: "Palais Royal",
    lat: 48.8637,
    lng: 2.3372,
    category: "Palace & Courtyard",
    kicker: "Iconic Paris · Architecture",
    description:
      "A 17th-century royal palace whose courtyard holds Buren's striped columns — a favourite Parisian shortcut.",
    detail:
      "Built for Cardinal Richelieu in 1633 and later home to the Duke of Orléans, the Palais Royal now houses the Conseil d'État. The Cour d'Honneur was filled in 1986 with Daniel Buren's 260 striped columns, an installation that scandalised the city and is now one of its most photographed courtyards.",
    scores: {
      scenic: 9,
      hidden: 3,
      historic: 9,
      architecture: 10,
      nature: 5,
      food: 4,
      popularity: 8,
    },
    interests: ["architecture", "historic", "iconic", "art"],
    visitMinutes: 8,
    arrondissement: 1,
    neighborhood: "Palais Royal",
  },
  {
    id: "jardin-palais-royal",
    name: "Jardin du Palais Royal",
    lat: 48.865,
    lng: 2.3376,
    category: "Garden",
    kicker: "Parks & Gardens · Local Paris",
    description:
      "An arcaded garden of clipped limes and fountains, sealed off from the traffic on all four sides.",
    detail:
      "One of the calmest places in the 1st arrondissement: gravel walks, a central fountain, and galleries of old-fashioned shops selling medals, pipes and antique toys. Colette lived above the north-west arcade for the last years of her life.",
    scores: {
      scenic: 9,
      hidden: 4,
      historic: 8,
      architecture: 8,
      nature: 9,
      food: 5,
      popularity: 7,
    },
    interests: ["parks", "quiet", "romantic", "architecture"],
    visitMinutes: 10,
    arrondissement: 1,
    neighborhood: "Palais Royal",
  },
  {
    id: "galerie-vivienne",
    name: "Galerie Vivienne",
    lat: 48.8664,
    lng: 2.3402,
    category: "Historic Passage",
    kicker: "Hidden Gem · Architecture",
    description:
      "One of Paris's most elegant covered passages, opened in 1826, known for mosaic floors and a glass roof.",
    detail:
      "Neoclassical goddesses, nymphs and garlands run above shopfronts; underfoot, Giandomenico Facchina's mosaic. The passage still holds a century-old bookshop, a wine merchant and a tearoom, and it stays dry and quiet whatever the weather is doing on rue Vivienne.",
    scores: {
      scenic: 10,
      hidden: 7,
      historic: 9,
      architecture: 10,
      nature: 1,
      food: 6,
      popularity: 6,
    },
    interests: ["architecture", "hidden", "historic", "bookshops", "romantic"],
    visitMinutes: 7,
    arrondissement: 2,
    neighborhood: "Bourse",
  },
  {
    id: "passage-panoramas",
    name: "Passage des Panoramas",
    lat: 48.8712,
    lng: 2.3416,
    category: "Historic Passage",
    kicker: "Historic Paris · Food",
    description:
      "The oldest covered passage in Paris, 1799 — now a crowded little corridor of stamp dealers and bistros.",
    detail:
      "The first Paris arcade lit by gas. Today it is scruffier and livelier than Vivienne: philatelists, engravers, and a dense row of small restaurants where locals eat elbow to elbow at lunchtime.",
    scores: {
      scenic: 8,
      hidden: 6,
      historic: 10,
      architecture: 7,
      nature: 1,
      food: 9,
      popularity: 6,
    },
    interests: ["historic", "hidden", "food", "local", "architecture"],
    visitMinutes: 8,
    arrondissement: 2,
    neighborhood: "Grands Boulevards",
  },
  {
    id: "passage-grand-cerf",
    name: "Passage du Grand Cerf",
    lat: 48.8646,
    lng: 2.3496,
    category: "Historic Passage",
    kicker: "Hidden Gem · Art & Galleries",
    description:
      "The tallest of the arcades, twelve metres of glass roof above independent design studios.",
    detail:
      "Rebuilt in 1825 on the site of a coaching inn, the Grand Cerf has the highest glazed roof of any Paris passage. Its tenants are mostly makers — jewellers, lighting designers, a bead shop — and it is usually almost empty.",
    scores: {
      scenic: 8,
      hidden: 9,
      historic: 8,
      architecture: 9,
      nature: 1,
      food: 4,
      popularity: 3,
    },
    interests: ["hidden", "architecture", "art", "quiet", "local"],
    visitMinutes: 6,
    arrondissement: 2,
    neighborhood: "Montorgueil",
  },
  {
    id: "rue-montorgueil",
    name: "Rue Montorgueil",
    lat: 48.865,
    lng: 2.3468,
    category: "Market Street",
    kicker: "Local Favorite · Food",
    description:
      "A pedestrian market street of fishmongers, cheese counters and terraces that never quite empties.",
    detail:
      "The surviving spine of the old Les Halles food quarter. Stohrer, opened 1730 by Louis XV's pastry chef, still sells baba au rhum halfway down. Best late morning, when the stalls are out and the street belongs to the neighbourhood.",
    scores: {
      scenic: 7,
      hidden: 3,
      historic: 7,
      architecture: 5,
      nature: 1,
      food: 10,
      popularity: 8,
    },
    interests: ["food", "cafes", "local", "historic"],
    visitMinutes: 12,
    arrondissement: 2,
    neighborhood: "Montorgueil",
  },
  {
    id: "saint-eustache",
    name: "Église Saint-Eustache",
    lat: 48.8635,
    lng: 2.3452,
    category: "Church",
    kicker: "Architecture · Historic Paris",
    description:
      "Gothic bones in Renaissance dress, with the largest pipe organ in France.",
    detail:
      "A hundred years in the building (1532–1632), Saint-Eustache carries Gothic vaults on classical columns. Molière was baptised here, Louis XIV took communion here, and the organ recitals on Sunday afternoons are free.",
    scores: {
      scenic: 8,
      hidden: 5,
      historic: 9,
      architecture: 10,
      nature: 1,
      food: 2,
      popularity: 6,
    },
    interests: ["architecture", "historic", "art"],
    visitMinutes: 10,
    arrondissement: 1,
    neighborhood: "Les Halles",
  },
  {
    id: "place-des-vosges",
    name: "Place des Vosges",
    lat: 48.8555,
    lng: 2.3655,
    category: "Square",
    kicker: "Iconic Paris · Architecture",
    description:
      "The oldest planned square in Paris: red brick, blue slate, and thirty-six identical pavilions.",
    detail:
      "Completed in 1612 as the Place Royale. The arcades run unbroken around all four sides, the lawns fill with readers on any warm afternoon, and Victor Hugo's apartment at number 6 is free to visit.",
    scores: {
      scenic: 10,
      hidden: 2,
      historic: 10,
      architecture: 10,
      nature: 7,
      food: 5,
      popularity: 9,
    },
    interests: ["iconic", "architecture", "historic", "parks", "romantic"],
    visitMinutes: 12,
    arrondissement: 4,
    neighborhood: "Le Marais",
  },
  {
    id: "jardin-anne-frank",
    name: "Jardin Anne Frank",
    lat: 48.8613,
    lng: 2.3577,
    category: "Garden",
    kicker: "Hidden Gem · Parks & Gardens",
    description:
      "A walled garden hidden behind a Marais courtyard, with a cutting from the Amsterdam chestnut tree.",
    detail:
      "Reached through an unmarked passage off impasse Berthaud. Three linked garden rooms — a pergola, an orchard, a lawn — almost nobody finds them by accident. A sapling grown from the chestnut Anne Frank watched from the annexe grows here.",
    scores: {
      scenic: 8,
      hidden: 10,
      historic: 6,
      architecture: 4,
      nature: 10,
      food: 1,
      popularity: 2,
    },
    interests: ["hidden", "parks", "quiet", "local"],
    visitMinutes: 8,
    arrondissement: 3,
    neighborhood: "Le Marais",
  },
  {
    id: "hotel-soubise",
    name: "Hôtel de Soubise",
    lat: 48.86,
    lng: 2.3595,
    category: "Mansion",
    kicker: "Architecture · Historic Paris",
    description:
      "A rococo palace behind a colonnaded court of honour, now the National Archives.",
    detail:
      "The 1375 medieval turrets on rue des Archives belong to the older Hôtel de Clisson; behind them, Delamair's 1705 horseshoe courtyard opens onto some of the finest rococo interiors in France. The garden at the back is public and almost always empty.",
    scores: {
      scenic: 9,
      hidden: 7,
      historic: 10,
      architecture: 10,
      nature: 5,
      food: 1,
      popularity: 4,
    },
    interests: ["architecture", "historic", "hidden", "art"],
    visitMinutes: 10,
    arrondissement: 3,
    neighborhood: "Le Marais",
  },
  {
    id: "marche-enfants-rouges",
    name: "Marché des Enfants Rouges",
    lat: 48.8632,
    lng: 2.3625,
    category: "Covered Market",
    kicker: "Food · Local Favorite",
    description:
      "The oldest covered market in Paris, 1615 — now a dozen kitchens under one iron roof.",
    detail:
      "Named for the red uniforms of the orphanage that once stood here. Moroccan, Japanese, Italian and Lebanese counters share communal tables; go before 1pm or expect to hover for a seat.",
    scores: {
      scenic: 6,
      hidden: 5,
      historic: 8,
      architecture: 4,
      nature: 1,
      food: 10,
      popularity: 7,
    },
    interests: ["food", "local", "historic", "cafes"],
    visitMinutes: 15,
    arrondissement: 3,
    neighborhood: "Haut Marais",
  },
  {
    id: "musee-carnavalet",
    name: "Musée Carnavalet",
    lat: 48.8573,
    lng: 2.3627,
    category: "Museum",
    kicker: "Historic Paris · Art & Galleries",
    description:
      "The history of Paris itself, in two Renaissance mansions with free permanent collections.",
    detail:
      "Shop signs, revolutionary relics, Proust's cork-lined bedroom. Even without going in, the twin courtyards and the orangery garden are worth the two-minute walk through.",
    scores: {
      scenic: 8,
      hidden: 4,
      historic: 10,
      architecture: 9,
      nature: 4,
      food: 2,
      popularity: 6,
    },
    interests: ["historic", "art", "architecture"],
    visitMinutes: 12,
    arrondissement: 3,
    neighborhood: "Le Marais",
  },
  {
    id: "rue-des-rosiers",
    name: "Rue des Rosiers",
    lat: 48.8571,
    lng: 2.3592,
    category: "Historic Street",
    kicker: "Food · Historic Paris",
    description:
      "The heart of the old Jewish quarter: bakeries, falafel counters and hand-painted signs.",
    detail:
      "A narrow street that has kept its trade for a century and a half — Sacha Finkelsztajn's yellow shopfront, the queue outside L'As du Fallafel, Hebrew lettering above doorways now shared with fashion boutiques.",
    scores: {
      scenic: 7,
      hidden: 4,
      historic: 9,
      architecture: 6,
      nature: 1,
      food: 9,
      popularity: 8,
    },
    interests: ["food", "historic", "local", "cafes"],
    visitMinutes: 10,
    arrondissement: 4,
    neighborhood: "Le Marais",
  },
  {
    id: "village-saint-paul",
    name: "Village Saint-Paul",
    lat: 48.8544,
    lng: 2.3609,
    category: "Courtyards",
    kicker: "Hidden Gem · Art & Galleries",
    description:
      "Five linked courtyards of antique dealers, tucked inside a medieval block.",
    detail:
      "Built into the grounds of the vanished Hôtel Saint-Pol. The courtyards connect by low archways and hold restorers, print dealers and a wine bar; a surviving stretch of Philippe Auguste's 12th-century city wall stands one street away.",
    scores: {
      scenic: 8,
      hidden: 9,
      historic: 9,
      architecture: 7,
      nature: 2,
      food: 4,
      popularity: 3,
    },
    interests: ["hidden", "art", "historic", "quiet", "local"],
    visitMinutes: 12,
    arrondissement: 4,
    neighborhood: "Saint-Paul",
  },
  {
    id: "rue-des-barres",
    name: "Rue des Barres",
    lat: 48.8552,
    lng: 2.3536,
    category: "Historic Street",
    kicker: "Hidden Gem · Historic Paris",
    description:
      "A quiet medieval-feeling street beside Saint-Gervais, a world away from the quai.",
    detail:
      "Cobbles, a stepped incline, half-timbered gables and the flying buttresses of Saint-Gervais overhead. One café puts tables out in good weather; otherwise you may have the street to yourself.",
    scores: {
      scenic: 9,
      hidden: 9,
      historic: 10,
      architecture: 8,
      nature: 1,
      food: 4,
      popularity: 3,
    },
    interests: ["hidden", "historic", "quiet", "romantic", "architecture"],
    visitMinutes: 5,
    arrondissement: 4,
    neighborhood: "Saint-Gervais",
  },
  {
    id: "saint-gervais",
    name: "Saint-Gervais-Saint-Protais",
    lat: 48.8556,
    lng: 2.3542,
    category: "Church",
    kicker: "Architecture · Historic Paris",
    description:
      "Flamboyant Gothic behind the first classical façade built in Paris.",
    detail:
      "The interior is dim, tall and usually silent apart from the monastic community that sings the offices here. The elm in the square outside marks the spot where justice was dispensed in the Middle Ages.",
    scores: {
      scenic: 8,
      hidden: 7,
      historic: 9,
      architecture: 9,
      nature: 2,
      food: 1,
      popularity: 4,
    },
    interests: ["architecture", "historic", "quiet", "hidden"],
    visitMinutes: 8,
    arrondissement: 4,
    neighborhood: "Saint-Gervais",
  },
  {
    id: "ile-saint-louis",
    name: "Île Saint-Louis",
    lat: 48.852,
    lng: 2.357,
    category: "Island",
    kicker: "Romantic · Iconic Paris",
    description:
      "A single 17th-century street down the spine of an island, with quays on both sides.",
    detail:
      "Laid out in one go in the 1660s and barely altered since. Rue Saint-Louis-en-l'Île runs the length of it; the quais below the plane trees are the best place in Paris to sit with an ice cream and watch the river work.",
    scores: {
      scenic: 10,
      hidden: 3,
      historic: 9,
      architecture: 9,
      nature: 6,
      food: 7,
      popularity: 9,
    },
    interests: ["romantic", "iconic", "historic", "architecture", "quiet"],
    visitMinutes: 12,
    arrondissement: 4,
    neighborhood: "Île Saint-Louis",
  },
  {
    id: "square-vert-galant",
    name: "Square du Vert-Galant",
    lat: 48.857,
    lng: 2.34,
    category: "Riverside Garden",
    kicker: "Romantic · Parks & Gardens",
    description:
      "The prow of the Île de la Cité, seven metres below the traffic and level with the Seine.",
    detail:
      "A willow, a few benches, and the river splitting around you. Named for Henri IV — the 'green gallant' — whose statue stands on the bridge above. The best free sunset in the 1st arrondissement.",
    scores: {
      scenic: 10,
      hidden: 6,
      historic: 8,
      architecture: 5,
      nature: 9,
      food: 1,
      popularity: 6,
    },
    interests: ["romantic", "parks", "quiet", "iconic"],
    visitMinutes: 10,
    arrondissement: 1,
    neighborhood: "Île de la Cité",
  },
  {
    id: "place-dauphine",
    name: "Place Dauphine",
    lat: 48.8564,
    lng: 2.3416,
    category: "Square",
    kicker: "Local Paris · Historic Paris",
    description:
      "A triangular tree-shaded square where the noise of the city simply stops.",
    detail:
      "Laid out in 1607, the second of Henri IV's royal squares. Boules under the chestnuts, two restaurants, and residents who have been here for decades. Yves Montand and Simone Signoret lived at number 15.",
    scores: {
      scenic: 9,
      hidden: 7,
      historic: 9,
      architecture: 8,
      nature: 6,
      food: 5,
      popularity: 5,
    },
    interests: ["quiet", "historic", "romantic", "architecture"],
    visitMinutes: 8,
    arrondissement: 1,
    neighborhood: "Île de la Cité",
  },
  {
    id: "cour-commerce",
    name: "Cour du Commerce Saint-André",
    lat: 48.8534,
    lng: 2.3392,
    category: "Historic Passage",
    kicker: "Hidden Gem · Cafés",
    description:
      "A cobbled 1776 alley where the guillotine was tested and the first Paris café still trades.",
    detail:
      "Marat printed L'Ami du Peuple at number 8; Doctor Guillotin tried his machine on sheep next door. Le Procope, opened 1686, backs onto the passage. A tower of Philippe Auguste's wall is visible through a window at number 4.",
    scores: {
      scenic: 9,
      hidden: 8,
      historic: 10,
      architecture: 7,
      nature: 1,
      food: 7,
      popularity: 5,
    },
    interests: ["hidden", "historic", "cafes", "architecture"],
    visitMinutes: 7,
    arrondissement: 6,
    neighborhood: "Odéon",
  },
  {
    id: "shakespeare-company",
    name: "Shakespeare and Company",
    lat: 48.8526,
    lng: 2.347,
    category: "Bookshop",
    kicker: "Bookshops · Iconic Paris",
    description:
      "The English-language bookshop facing Notre-Dame, with beds between the shelves.",
    detail:
      "George Whitman's 1951 shop, heir to Sylvia Beach's name. Writers still sleep upstairs in exchange for a few hours' work. Upstairs there is a piano, a typewriter and a reading room nobody will hurry you out of.",
    scores: {
      scenic: 8,
      hidden: 2,
      historic: 7,
      architecture: 5,
      nature: 1,
      food: 4,
      popularity: 9,
    },
    interests: ["bookshops", "iconic", "cafes", "romantic"],
    visitMinutes: 12,
    arrondissement: 5,
    neighborhood: "Latin Quarter",
  },
  {
    id: "jardin-luxembourg",
    name: "Jardin du Luxembourg",
    lat: 48.8462,
    lng: 2.3372,
    category: "Garden",
    kicker: "Parks & Gardens · Iconic Paris",
    description:
      "Twenty-three hectares of gravel, green chairs and toy sailboats on a round basin.",
    detail:
      "Marie de Médicis' garden of 1612, half formal French, half English. The Medici Fountain in its shaded alley is the most romantic corner; the orchard at the south-west holds hundreds of heritage apple varieties.",
    scores: {
      scenic: 10,
      hidden: 1,
      historic: 9,
      architecture: 7,
      nature: 10,
      food: 3,
      popularity: 10,
    },
    interests: ["parks", "iconic", "romantic", "quiet"],
    visitMinutes: 20,
    arrondissement: 6,
    neighborhood: "Odéon",
  },
  {
    id: "rue-mouffetard",
    name: "Rue Mouffetard",
    lat: 48.8425,
    lng: 2.3495,
    category: "Market Street",
    kicker: "Food · Local Favorite",
    description:
      "A Roman road turned market street, tumbling downhill past cheese shops and student bars.",
    detail:
      "One of the oldest streets in Paris and still a working market at the bottom end. Hemingway lived at number 74 on the neighbouring rue du Cardinal Lemoine and called this 'a wonderful narrow crowded market street'.",
    scores: {
      scenic: 8,
      hidden: 3,
      historic: 9,
      architecture: 6,
      nature: 1,
      food: 10,
      popularity: 8,
    },
    interests: ["food", "local", "historic", "cafes"],
    visitMinutes: 15,
    arrondissement: 5,
    neighborhood: "Mouffetard",
  },
  {
    id: "arenes-lutece",
    name: "Arènes de Lutèce",
    lat: 48.8452,
    lng: 2.3527,
    category: "Roman Ruin",
    kicker: "Hidden Gem · Historic Paris",
    description:
      "A 1st-century Roman amphitheatre, entered through a doorway on an ordinary street.",
    detail:
      "Lost for centuries, rediscovered in 1869 when a tram depot was dug. It seated 15,000; today old men play boules on the arena floor and children run the tiers. There is no sign worth the name outside.",
    scores: {
      scenic: 7,
      hidden: 10,
      historic: 10,
      architecture: 7,
      nature: 6,
      food: 1,
      popularity: 4,
    },
    interests: ["hidden", "historic", "quiet", "parks"],
    visitMinutes: 10,
    arrondissement: 5,
    neighborhood: "Latin Quarter",
  },
  {
    id: "canal-saint-martin",
    name: "Canal Saint-Martin",
    lat: 48.871,
    lng: 2.3665,
    category: "Canal",
    kicker: "Local Favorite · Romantic",
    description:
      "Iron footbridges, plane trees and locks — the city's most unhurried waterway.",
    detail:
      "Napoleon's canal of 1802, now the spine of a neighbourhood of small bars and design shops. Sit on the quai with something from a nearby épicerie and watch a barge take twenty minutes to drop through a lock.",
    scores: {
      scenic: 9,
      hidden: 4,
      historic: 7,
      architecture: 5,
      nature: 8,
      food: 8,
      popularity: 7,
    },
    interests: ["local", "romantic", "cafes", "parks", "quiet"],
    visitMinutes: 15,
    arrondissement: 10,
    neighborhood: "Canal Saint-Martin",
  },
  {
    id: "jardin-tuileries",
    name: "Jardin des Tuileries",
    lat: 48.8635,
    lng: 2.3272,
    category: "Garden",
    kicker: "Iconic Paris · Parks & Gardens",
    description:
      "Le Nôtre's grand axis of gravel, statuary and round ponds between the Louvre and Concorde.",
    detail:
      "The blueprint for the formal French garden, opened to the public in 1667. Pull a green chair to the edge of the octagonal basin and you have the best seat on the Right Bank.",
    scores: {
      scenic: 9,
      hidden: 1,
      historic: 9,
      architecture: 7,
      nature: 9,
      food: 3,
      popularity: 10,
    },
    interests: ["parks", "iconic", "romantic", "art"],
    visitMinutes: 15,
    arrondissement: 1,
    neighborhood: "Tuileries",
  },
  {
    id: "pont-des-arts",
    name: "Pont des Arts",
    lat: 48.8583,
    lng: 2.3374,
    category: "Bridge",
    kicker: "Romantic · Iconic Paris",
    description:
      "A wooden-decked pedestrian bridge with the best framed view of the Île de la Cité.",
    detail:
      "The first iron bridge in Paris, rebuilt in 1984 and now free of its padlocks. Artists work along the deck; at dusk the light down the river towards the Pont Neuf is the reason people move here.",
    scores: {
      scenic: 10,
      hidden: 2,
      historic: 7,
      architecture: 7,
      nature: 5,
      food: 1,
      popularity: 9,
    },
    interests: ["romantic", "iconic", "art"],
    visitMinutes: 6,
    arrondissement: 6,
    neighborhood: "Saint-Germain",
  },
  {
    id: "cour-rohan",
    name: "Cour de Rohan",
    lat: 48.8531,
    lng: 2.3383,
    category: "Courtyards",
    kicker: "Hidden Gem · Historic Paris",
    description:
      "Three linked private courtyards with a surviving Renaissance mounting block.",
    detail:
      "Off the Cour du Commerce, gated but usually open in the daytime. Wisteria, a well, and the last 'pas-de-mule' in Paris — the stone step noblewomen used to climb onto their mules.",
    scores: {
      scenic: 9,
      hidden: 10,
      historic: 9,
      architecture: 8,
      nature: 4,
      food: 1,
      popularity: 2,
    },
    interests: ["hidden", "quiet", "historic", "architecture", "romantic"],
    visitMinutes: 5,
    arrondissement: 6,
    neighborhood: "Odéon",
  },
  {
    id: "place-du-marche-sainte-catherine",
    name: "Place du Marché Sainte-Catherine",
    lat: 48.8558,
    lng: 2.3634,
    category: "Square",
    kicker: "Cafés · Local Paris",
    description:
      "A small tree-filled square of terraces, hidden one street off the rue Saint-Antoine.",
    detail:
      "Built on the site of a priory and pedestrianised long before the rest of the Marais. Four or five restaurants put tables under the trees; in the evening it feels like a village square that lost its village.",
    scores: {
      scenic: 8,
      hidden: 8,
      historic: 7,
      architecture: 6,
      nature: 6,
      food: 8,
      popularity: 4,
    },
    interests: ["cafes", "quiet", "romantic", "local", "food"],
    visitMinutes: 8,
    arrondissement: 4,
    neighborhood: "Le Marais",
  },
  {
    id: "fontaine-stravinsky",
    name: "Fontaine Stravinsky",
    lat: 48.859,
    lng: 2.3512,
    category: "Fountain",
    kicker: "Art & Galleries · Iconic Paris",
    description:
      "Sixteen mechanical sculptures spitting water beside the Centre Pompidou.",
    detail:
      "Niki de Saint Phalle's colours against Jean Tinguely's black machines, 1983. Loud, absurd and entirely un-Parisian, which is the point. The terraces on the south side get the afternoon sun.",
    scores: {
      scenic: 7,
      hidden: 3,
      historic: 4,
      architecture: 6,
      nature: 3,
      food: 6,
      popularity: 8,
    },
    interests: ["art", "iconic", "cafes"],
    visitMinutes: 6,
    arrondissement: 4,
    neighborhood: "Beaubourg",
  },
  {
    id: "galerie-vero-dodat",
    name: "Galerie Véro-Dodat",
    lat: 48.8624,
    lng: 2.3406,
    category: "Historic Passage",
    kicker: "Hidden Gem · Architecture",
    description:
      "Black-and-white tiled floors, mahogany shopfronts and brass — the most theatrical arcade.",
    detail:
      "Opened 1826 by two charcutiers, restored to its neoclassical gloom. Luthiers and a couture house share it now, and it is almost always empty enough to hear your own footsteps.",
    scores: {
      scenic: 9,
      hidden: 9,
      historic: 9,
      architecture: 10,
      nature: 1,
      food: 3,
      popularity: 3,
    },
    interests: ["hidden", "architecture", "historic", "quiet", "art"],
    visitMinutes: 6,
    arrondissement: 1,
    neighborhood: "Louvre",
  },
  {
    id: "rue-de-furstemberg",
    name: "Place de Furstemberg",
    lat: 48.8541,
    lng: 2.3345,
    category: "Square",
    kicker: "Romantic · Hidden Gem",
    description:
      "Four paulownia trees and a white globe lamp — reputedly the most romantic square in Paris.",
    detail:
      "Delacroix kept his studio and garden off this square; it is now a small museum. The paulownias flower purple in late April and the square is lit at night like a stage set.",
    scores: {
      scenic: 10,
      hidden: 8,
      historic: 8,
      architecture: 8,
      nature: 6,
      food: 2,
      popularity: 4,
    },
    interests: ["romantic", "quiet", "hidden", "art", "architecture"],
    visitMinutes: 6,
    arrondissement: 6,
    neighborhood: "Saint-Germain",
  },
  {
    id: "passage-verdeau",
    name: "Passage Verdeau",
    lat: 48.8735,
    lng: 2.3437,
    category: "Historic Passage",
    kicker: "Bookshops · Hidden Gem",
    description:
      "Old photographs, prints and antiquarian books under a fishbone glass roof.",
    detail:
      "The quietest of the linked northern passages. Dealers in vintage cameras and 19th-century engravings; the light through the roof at midday is worth the detour on its own.",
    scores: {
      scenic: 8,
      hidden: 9,
      historic: 8,
      architecture: 8,
      nature: 1,
      food: 3,
      popularity: 3,
    },
    interests: ["bookshops", "hidden", "architecture", "historic", "quiet"],
    visitMinutes: 7,
    arrondissement: 9,
    neighborhood: "Grands Boulevards",
  },
  {
    id: "quai-de-bourbon",
    name: "Quai de Bourbon",
    lat: 48.8541,
    lng: 2.3593,
    category: "Riverside",
    kicker: "Architecture · Romantic",
    description:
      "The northern quay of Île Saint-Louis, with steps down to the water's edge.",
    detail:
      "Camille Claudel worked at number 19. From the tip of the island you look straight at the flying buttresses of Notre-Dame across the smaller arm of the Seine.",
    scores: {
      scenic: 10,
      hidden: 6,
      historic: 8,
      architecture: 8,
      nature: 7,
      food: 2,
      popularity: 6,
    },
    interests: ["quiet", "romantic", "architecture", "iconic"],
    visitMinutes: 8,
    arrondissement: 4,
    neighborhood: "Île Saint-Louis",
  },
];

assertValidPoiDataset(CURATED_POIS);

export const POIS = CURATED_POIS;

export const poiById = (id: string) => POIS.find((p) => p.id === id);
