/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as NavigateRouteImport } from './routes/navigate'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as WanderRouteImport } from './routes/wander'
import { Route as ApiV1GeocodingReverseRouteImport } from './routes/api/v1/geocoding/reverse'
import { Route as ApiV1GeocodingSearchRouteImport } from './routes/api/v1/geocoding/search'
import { Route as ApiV1RoutingMatrixRouteImport } from './routes/api/v1/routing/matrix'
import { Route as ApiV1RoutingRoutesRouteImport } from './routes/api/v1/routing/routes'
import { Route as ApiV1RoutingViaRouteImport } from './routes/api/v1/routing/via'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateRoute = NavigateRouteImport.update({
  id: '/navigate',
  path: '/navigate',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const WanderRoute = WanderRouteImport.update({
  id: '/wander',
  path: '/wander',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GeocodingReverseRoute = ApiV1GeocodingReverseRouteImport.update({
  id: '/api/v1/geocoding/reverse',
  path: '/api/v1/geocoding/reverse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GeocodingSearchRoute = ApiV1GeocodingSearchRouteImport.update({
  id: '/api/v1/geocoding/search',
  path: '/api/v1/geocoding/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RoutingMatrixRoute = ApiV1RoutingMatrixRouteImport.update({
  id: '/api/v1/routing/matrix',
  path: '/api/v1/routing/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RoutingRoutesRoute = ApiV1RoutingRoutesRouteImport.update({
  id: '/api/v1/routing/routes',
  path: '/api/v1/routing/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RoutingViaRoute = ApiV1RoutingViaRouteImport.update({
  id: '/api/v1/routing/via',
  path: '/api/v1/routing/via',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/explore': typeof ExploreRoute
  '/navigate': typeof NavigateRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/shared': typeof SharedRoute
  '/wander': typeof WanderRoute
  '/api/v1/geocoding/reverse': typeof ApiV1GeocodingReverseRoute
  '/api/v1/geocoding/search': typeof ApiV1GeocodingSearchRoute
  '/api/v1/routing/matrix': typeof ApiV1RoutingMatrixRoute
  '/api/v1/routing/routes': typeof ApiV1RoutingRoutesRoute
  '/api/v1/routing/via': typeof ApiV1RoutingViaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/explore': typeof ExploreRoute
  '/navigate': typeof NavigateRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/shared': typeof SharedRoute
  '/wander': typeof WanderRoute
  '/api/v1/geocoding/reverse': typeof ApiV1GeocodingReverseRoute
  '/api/v1/geocoding/search': typeof ApiV1GeocodingSearchRoute
  '/api/v1/routing/matrix': typeof ApiV1RoutingMatrixRoute
  '/api/v1/routing/routes': typeof ApiV1RoutingRoutesRoute
  '/api/v1/routing/via': typeof ApiV1RoutingViaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/explore': typeof ExploreRoute
  '/navigate': typeof NavigateRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/shared': typeof SharedRoute
  '/wander': typeof WanderRoute
  '/api/v1/geocoding/reverse': typeof ApiV1GeocodingReverseRoute
  '/api/v1/geocoding/search': typeof ApiV1GeocodingSearchRoute
  '/api/v1/routing/matrix': typeof ApiV1RoutingMatrixRoute
  '/api/v1/routing/routes': typeof ApiV1RoutingRoutesRoute
  '/api/v1/routing/via': typeof ApiV1RoutingViaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete'
    | '/explore'
    | '/navigate'
    | '/plan'
    | '/profile'
    | '/saved'
    | '/shared'
    | '/wander'
    | '/api/v1/geocoding/reverse'
    | '/api/v1/geocoding/search'
    | '/api/v1/routing/matrix'
    | '/api/v1/routing/routes'
    | '/api/v1/routing/via'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete'
    | '/explore'
    | '/navigate'
    | '/plan'
    | '/profile'
    | '/saved'
    | '/shared'
    | '/wander'
    | '/api/v1/geocoding/reverse'
    | '/api/v1/geocoding/search'
    | '/api/v1/routing/matrix'
    | '/api/v1/routing/routes'
    | '/api/v1/routing/via'
  id:
    | '__root__'
    | '/'
    | '/complete'
    | '/explore'
    | '/navigate'
    | '/plan'
    | '/profile'
    | '/saved'
    | '/shared'
    | '/wander'
    | '/api/v1/geocoding/reverse'
    | '/api/v1/geocoding/search'
    | '/api/v1/routing/matrix'
    | '/api/v1/routing/routes'
    | '/api/v1/routing/via'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteRoute: typeof CompleteRoute
  ExploreRoute: typeof ExploreRoute
  NavigateRoute: typeof NavigateRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SharedRoute: typeof SharedRoute
  WanderRoute: typeof WanderRoute
  ApiV1GeocodingReverseRoute: typeof ApiV1GeocodingReverseRoute
  ApiV1GeocodingSearchRoute: typeof ApiV1GeocodingSearchRoute
  ApiV1RoutingMatrixRoute: typeof ApiV1RoutingMatrixRoute
  ApiV1RoutingRoutesRoute: typeof ApiV1RoutingRoutesRoute
  ApiV1RoutingViaRoute: typeof ApiV1RoutingViaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigate': {
      id: '/navigate'
      path: '/navigate'
      fullPath: '/navigate'
      preLoaderRoute: typeof NavigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wander': {
      id: '/wander'
      path: '/wander'
      fullPath: '/wander'
      preLoaderRoute: typeof WanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/geocoding/reverse': {
      id: '/api/v1/geocoding/reverse'
      path: '/api/v1/geocoding/reverse'
      fullPath: '/api/v1/geocoding/reverse'
      preLoaderRoute: typeof ApiV1GeocodingReverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/geocoding/search': {
      id: '/api/v1/geocoding/search'
      path: '/api/v1/geocoding/search'
      fullPath: '/api/v1/geocoding/search'
      preLoaderRoute: typeof ApiV1GeocodingSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/routing/matrix': {
      id: '/api/v1/routing/matrix'
      path: '/api/v1/routing/matrix'
      fullPath: '/api/v1/routing/matrix'
      preLoaderRoute: typeof ApiV1RoutingMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/routing/routes': {
      id: '/api/v1/routing/routes'
      path: '/api/v1/routing/routes'
      fullPath: '/api/v1/routing/routes'
      preLoaderRoute: typeof ApiV1RoutingRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/routing/via': {
      id: '/api/v1/routing/via'
      path: '/api/v1/routing/via'
      fullPath: '/api/v1/routing/via'
      preLoaderRoute: typeof ApiV1RoutingViaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteRoute: CompleteRoute,
  ExploreRoute: ExploreRoute,
  NavigateRoute: NavigateRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SharedRoute: SharedRoute,
  WanderRoute: WanderRoute,
  ApiV1GeocodingReverseRoute: ApiV1GeocodingReverseRoute,
  ApiV1GeocodingSearchRoute: ApiV1GeocodingSearchRoute,
  ApiV1RoutingMatrixRoute: ApiV1RoutingMatrixRoute,
  ApiV1RoutingRoutesRoute: ApiV1RoutingRoutesRoute,
  ApiV1RoutingViaRoute: ApiV1RoutingViaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
