/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompleteRouteImport } from './routes/complete'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as NavigateRouteImport } from './routes/navigate'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as WanderRouteImport } from './routes/wander'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRoute = CompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigateRoute = NavigateRouteImport.update({
  id: '/navigate',
  path: '/navigate',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const WanderRoute = WanderRouteImport.update({
  id: '/wander',
  path: '/wander',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/explore': typeof ExploreRoute
  '/navigate': typeof NavigateRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/shared': typeof SharedRoute
  '/wander': typeof WanderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/explore': typeof ExploreRoute
  '/navigate': typeof NavigateRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/shared': typeof SharedRoute
  '/wander': typeof WanderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/complete': typeof CompleteRoute
  '/explore': typeof ExploreRoute
  '/navigate': typeof NavigateRoute
  '/plan': typeof PlanRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/shared': typeof SharedRoute
  '/wander': typeof WanderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete'
    | '/explore'
    | '/navigate'
    | '/plan'
    | '/profile'
    | '/saved'
    | '/shared'
    | '/wander'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete'
    | '/explore'
    | '/navigate'
    | '/plan'
    | '/profile'
    | '/saved'
    | '/shared'
    | '/wander'
  id:
    | '__root__'
    | '/'
    | '/complete'
    | '/explore'
    | '/navigate'
    | '/plan'
    | '/profile'
    | '/saved'
    | '/shared'
    | '/wander'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompleteRoute: typeof CompleteRoute
  ExploreRoute: typeof ExploreRoute
  NavigateRoute: typeof NavigateRoute
  PlanRoute: typeof PlanRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  SharedRoute: typeof SharedRoute
  WanderRoute: typeof WanderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete': {
      id: '/complete'
      path: '/complete'
      fullPath: '/complete'
      preLoaderRoute: typeof CompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigate': {
      id: '/navigate'
      path: '/navigate'
      fullPath: '/navigate'
      preLoaderRoute: typeof NavigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wander': {
      id: '/wander'
      path: '/wander'
      fullPath: '/wander'
      preLoaderRoute: typeof WanderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompleteRoute: CompleteRoute,
  ExploreRoute: ExploreRoute,
  NavigateRoute: NavigateRoute,
  PlanRoute: PlanRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SharedRoute: SharedRoute,
  WanderRoute: WanderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
